[build-system]
requires = ["setuptools>=61.0.0", "wheel", "pytest", "sphinx"]
build-backend = "setuptools.build_meta"

[project]
name = "tagstr"
version = "0.0.1"
description = "Collection of tag string demos, docs, and specs."
requires-python = ">=3.12"